#!/bin/bash

# http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

# add key for Mono Project
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list

sudo apt-get update && sudo apt-get upgrade

sudo apt-get install -y mono-devel mono-complete referenceassemblies-pcl monodevelop monodevelop-database monodevelop-nunit monodevelop-versioncontrol monodoc-browser asp.net-examples mono-xsp4

echo "Installed:"
mono --version
mcs --version

