#!/bin/bash

# http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

# add key for webupd8team
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
# accept license, install, and set to use
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-get install -y oracle-java8-installer oracle-java8-set-default
#sudo update-java-alternatives -s java-8-oracle


echo "Java 8 installed."
java -version

